## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent freepdb1

{{- if .Values.server.database }}
  {{- $secretName := include "server.databasePrivSecret" . }}
  {{- $secret_existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
  {{- if not $secret_existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/component: database
    {{- include "global.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
    {{- if (has .Values.server.database.type (list "ADB-S" "ADB-FREE")) }}
  username: "ADMIN"
    {{- else }}
  username: "SYSTEM"
    {{- end }}
  password: {{ include "server.randomPassword" . | quote }}
  {{- end }}
{{- end }}