## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore sidb ollama

# Example Helm Values for Containerized ADB
server:
  replicaCount: 1
  image:
    repository: localhost/ai-optimizer-server
    tag: latest
  database:
    type: "ADB-FREE"
    image:
      repository: container-registry.oracle.com/database/adb-free
      tag: latest
client:
  replicaCount: 1
  image:
    repository: localhost/ai-optimizer-client
    tag: latest
ollama:
  enabled: true
  replicaCount: 1
  models:
    enabled: true
