-- Racing Team Analytics
-- Oracle Database synthetic seed pack
-- Scope: core relational schema + sample data for Driver001 to Driver100
-- Notes:
--   * Uses Oracle identity columns and CLOB for document text.
--   * Avoids person-shaped data; drivers are simulator assignments only.
--
-- spell-checker: ignore CLOB VARCHAR

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

-------------------------------------------------------------------------------
-- DROP TABLES (optional, safe order)
-------------------------------------------------------------------------------
BEGIN
  FOR t IN (SELECT *
              FROM user_tables
             WHERE UPPER(table_name) LIKE '%OCI_COHERE_EMBED_ENGLISH%'
               AND VECTOR_INDEX_TYPE is NULL)
  LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE "' || t.table_name || '" PURGE';
    EXCEPTION
      WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE team_race_points PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE performance_metrics PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE incidents PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE pit_stops PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE race_results PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE races PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE drivers PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE teams PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-------------------------------------------------------------------------------
-- TABLES
-------------------------------------------------------------------------------
CREATE TABLE teams (
  team_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_name         VARCHAR2(100) NOT NULL,
  engineering_focus VARCHAR2(100) NOT NULL,
  garage_location   VARCHAR2(100) NOT NULL
);

CREATE TABLE drivers (
  driver_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_code       VARCHAR2(20) NOT NULL UNIQUE,
  driver_label      VARCHAR2(20) NOT NULL UNIQUE,
  driver_group      VARCHAR2(40) NOT NULL,
  simulator_rig     VARCHAR2(40) NOT NULL,
  vehicle_setup     VARCHAR2(80) NOT NULL,
  team_id           NUMBER NOT NULL,
  driving_style     VARCHAR2(80) NOT NULL,
  skill_profile     VARCHAR2(200) NOT NULL,
  CONSTRAINT fk_drivers_team FOREIGN KEY (team_id) REFERENCES teams(team_id)
);

CREATE TABLE races (
  race_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_name         VARCHAR2(100) NOT NULL,
  circuit           VARCHAR2(100) NOT NULL,
  country           VARCHAR2(80) NOT NULL,
  race_date         DATE NOT NULL,
  weather_condition VARCHAR2(80) NOT NULL
);

CREATE TABLE race_results (
  result_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_id           NUMBER NOT NULL,
  driver_id         NUMBER NOT NULL,
  qualifying_position NUMBER(3) NOT NULL,
  finish_position   NUMBER(3),
  points            NUMBER(5,2) DEFAULT 0 NOT NULL,
  fastest_lap       NUMBER(10,3),
  status            VARCHAR2(40) NOT NULL,
  penalties         VARCHAR2(200),
  CONSTRAINT fk_results_race FOREIGN KEY (race_id) REFERENCES races(race_id),
  CONSTRAINT fk_results_driver FOREIGN KEY (driver_id) REFERENCES drivers(driver_id)
);

CREATE TABLE pit_stops (
  pit_stop_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_id           NUMBER NOT NULL,
  driver_id         NUMBER NOT NULL,
  lap_number        NUMBER(4) NOT NULL,
  stop_duration_ms  NUMBER(8) NOT NULL,
  tyre_compound     VARCHAR2(20) NOT NULL,
  reason            VARCHAR2(120) NOT NULL,
  CONSTRAINT fk_pit_race FOREIGN KEY (race_id) REFERENCES races(race_id),
  CONSTRAINT fk_pit_driver FOREIGN KEY (driver_id) REFERENCES drivers(driver_id)
);

CREATE TABLE incidents (
  incident_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_id           NUMBER NOT NULL,
  driver_id         NUMBER NOT NULL,
  incident_type     VARCHAR2(60) NOT NULL,
  severity          VARCHAR2(20) NOT NULL,
  lap_number        NUMBER(4) NOT NULL,
  short_description VARCHAR2(400) NOT NULL,
  CONSTRAINT fk_inc_race FOREIGN KEY (race_id) REFERENCES races(race_id),
  CONSTRAINT fk_inc_driver FOREIGN KEY (driver_id) REFERENCES drivers(driver_id)
);

CREATE TABLE performance_metrics (
  metric_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id         NUMBER NOT NULL,
  race_id           NUMBER NOT NULL,
  avg_lap_time      NUMBER(10,3) NOT NULL,
  top_speed         NUMBER(6,2) NOT NULL,
  tyre_degradation   NUMBER(5,2) NOT NULL,
  overtakes         NUMBER(3) NOT NULL,
  mistakes          NUMBER(3) NOT NULL,
  CONSTRAINT fk_perf_driver FOREIGN KEY (driver_id) REFERENCES drivers(driver_id),
  CONSTRAINT fk_perf_race FOREIGN KEY (race_id) REFERENCES races(race_id)
);

CREATE TABLE team_race_points (
  team_race_point_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  race_id            NUMBER NOT NULL,
  team_id            NUMBER NOT NULL,
  points             NUMBER(5,2) NOT NULL,
  publication_status VARCHAR2(60) NOT NULL,
  race_control_note  VARCHAR2(400),
  recorded_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_team_points_race FOREIGN KEY (race_id) REFERENCES races(race_id),
  CONSTRAINT fk_team_points_team FOREIGN KEY (team_id) REFERENCES teams(team_id)
);

-------------------------------------------------------------------------------
-- TEAMS and DRIVERS
-- 20 teams of 5 drivers each. DBMS_RANDOM is left unseeded so the
-- synthetic-extension block below produces different pre-finale standings on
-- every reset, varying the championship finale answer when combined with the
-- late Round 6 team-points insert.
-------------------------------------------------------------------------------
DECLARE
  TYPE t_vc_arr IS TABLE OF VARCHAR2(100);

  v_team_names t_vc_arr := t_vc_arr(
    'Apex Dynamics',
    'Blue Torque',
    'Carbon Shift',
    'Delta Velocity',
    'Nova Circuit',
    'Quantum Apex',
    'Velocity Forge',
    'Titan Motorsport',
    'Phoenix Racing Lab',
    'Vertex GP',
    'Solstice Motorsport',
    'Helix Engineering',
    'Orbit Performance',
    'Catalyst Racing',
    'Strata GP',
    'Pulse Velocity',
    'Halo Speedworks',
    'Equinox Racing',
    'Synapse Motorsport',
    'Forge Edge Racing'
  );

  v_engineering_focuses t_vc_arr := t_vc_arr(
    'Aero Efficiency',
    'Battery Deployment',
    'Tyre Strategy',
    'Wet Setup',
    'Brake Stability',
    'Suspension Balance',
    'Pit Stop Execution',
    'Race Simulation',
    'Thermal Management',
    'Telemetry Analytics',
    'Cooling Optimization',
    'Energy Recovery',
    'Wind Tunnel Validation',
    'DRS Tuning',
    'Driver Coaching',
    'Race Strategy',
    'Setup Iteration',
    'Component Reliability',
    'Tyre Warmup',
    'Fuel Mapping'
  );

  v_garages t_vc_arr := t_vc_arr(
    'Garage A1',
    'Garage B2',
    'Garage C3',
    'Garage D4',
    'Garage E5',
    'Garage F6',
    'Garage G7',
    'Garage H8',
    'Garage I9',
    'Garage J10',
    'Garage K11',
    'Garage L12',
    'Garage M13',
    'Garage N14',
    'Garage O15',
    'Garage P16',
    'Garage Q17',
    'Garage R18',
    'Garage S19',
    'Garage T20'
  );

  v_driver_groups t_vc_arr := t_vc_arr(
    'Cohort A',
    'Cohort B',
    'Cohort C',
    'Cohort D',
    'Cohort E',
    'Cohort F',
    'Cohort G',
    'Cohort H',
    'Cohort I',
    'Cohort J'
  );

  v_vehicle_setups t_vc_arr := t_vc_arr(
    'High Downforce',
    'Balanced',
    'Low Drag',
    'Wet Weather',
    'Tyre Saver',
    'Qualifying Trim',
    'Race Pace',
    'Kerb Stability',
    'Traction Focus',
    'Energy Recovery'
  );

  v_driving_styles t_vc_arr := t_vc_arr(
    'Late Braker',
    'Tyre Saver',
    'Wet Specialist',
    'Defensive Racer',
    'Overtake Focused',
    'Consistency Focused',
    'Qualifying Specialist',
    'Strategy Led',
    'Smooth Inputs',
    'Aggressive Starter'
  );

  v_skills t_vc_arr := t_vc_arr(
    'Qualifying Pace',
    'Racecraft',
    'Tyre Management',
    'Wet Weather',
    'Strategy Awareness',
    'Defensive Driving',
    'Recovery Drive',
    'Consistency'
  );

  v_driver_code VARCHAR2(20);
  v_driver_label VARCHAR2(20);
  v_driver_group VARCHAR2(40);
  v_simulator_rig VARCHAR2(40);
  v_vehicle_setup VARCHAR2(80);
  v_driving_style VARCHAR2(80);
  v_skill VARCHAR2(100);
  v_team_id NUMBER;
BEGIN
  FOR i IN 1..20 LOOP
    INSERT INTO teams (team_name, engineering_focus, garage_location)
    VALUES (v_team_names(i), v_engineering_focuses(i), v_garages(i));
  END LOOP;

  FOR i IN 1..100 LOOP
    v_driver_code := 'Driver' || LPAD(i, 3, '0');
    v_driver_label := 'Driver ' || TO_CHAR(i);
    v_team_id := MOD(i - 1, 20) + 1;
    v_driver_group := v_driver_groups(MOD(i - 1, v_driver_groups.COUNT) + 1);
    v_simulator_rig := 'Rig ' || LPAD(MOD(i - 1, 25) + 1, 2, '0');
    v_vehicle_setup := v_vehicle_setups(MOD((i * 7) + 3, v_vehicle_setups.COUNT) + 1);
    v_driving_style := v_driving_styles(MOD((i * 7) + 6, v_driving_styles.COUNT) + 1);
    v_skill := v_skills(MOD((i * 7) + 9, v_skills.COUNT) + 1);

    INSERT INTO drivers (
      driver_code,
      driver_label,
      driver_group,
      simulator_rig,
      vehicle_setup,
      team_id,
      driving_style,
      skill_profile
    ) VALUES (
      v_driver_code,
      v_driver_label,
      v_driver_group,
      v_simulator_rig,
      v_vehicle_setup,
      v_team_id,
      v_driving_style,
      v_skill
    );
  END LOOP;

  COMMIT;
END;
/

-------------------------------------------------------------------------------
-- RACES
-------------------------------------------------------------------------------
INSERT INTO races (race_name, circuit, country, race_date, weather_condition) VALUES
('Round 1: Opening Sprint', 'Silverstone National', 'United Kingdom', DATE '2026-02-14', 'Dry, cool, windy');
INSERT INTO races (race_name, circuit, country, race_date, weather_condition) VALUES
('Round 2: Spring Challenge', 'Brands Hatch Indy', 'United Kingdom', DATE '2026-03-07', 'Dry, mild');
INSERT INTO races (race_name, circuit, country, race_date, weather_condition) VALUES
('Round 3: Rain Warning', 'Thruxton', 'United Kingdom', DATE '2026-03-28', 'Intermittent rain');
INSERT INTO races (race_name, circuit, country, race_date, weather_condition) VALUES
('Round 4: Technical Test', 'Donington Park', 'United Kingdom', DATE '2026-04-11', 'Dry, warm');
INSERT INTO races (race_name, circuit, country, race_date, weather_condition) VALUES
('Round 5: Mid-Season Cup', 'Oulton Park', 'United Kingdom', DATE '2026-04-25', 'Overcast, damp track');
INSERT INTO races (race_name, circuit, country, race_date, weather_condition) VALUES
('Round 6: Finale Preview', 'Snetterton 300', 'United Kingdom', DATE '2026-05-02', 'Dry, hot');

-------------------------------------------------------------------------------
-- RACE RESULTS (curated Driver001..Driver010 rows for Round 1 and Round 2)
-- Race 1 = race_id 1, Race 2 = race_id 2
-------------------------------------------------------------------------------
-- Round 1
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (1, 1, 4, 2, 18, 92.441, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (1, 2, 6, 5, 10, 93.105, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (1, 3, 1, 1, 25, 91.982, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (1, 4, 8, 6, 8, 93.774, 'Finished', 'Track limits warning');
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (1, 5, 10, 9, 2, 94.120, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (1, 6, 5, 4, 12, 92.864, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (1, 7, 7, 8, 4, 93.901, 'Finished', '5s penalty for unsafe release');
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (1, 8, 2, 3, 15, 92.530, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (1, 9, 9, 10, 1, 94.880, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (1, 10, 3, 7, 6, 93.450, 'Finished', '10s penalty for pit lane speeding');

-- Round 2
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (2, 1, 3, 1, 25, 89.910, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (2, 2, 5, 4, 12, 90.432, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (2, 3, 2, 3, 15, 90.015, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (2, 4, 1, 2, 18, 89.995, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (2, 5, 10, 8, 4, 91.240, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (2, 6, 6, 6, 8, 90.880, 'Finished', 'Track limits warning');
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (2, 7, 4, 5, 10, 90.500, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (2, 8, 8, 7, 6, 91.010, 'Finished', NULL);
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (2, 9, 7, 9, 2, 91.310, 'Finished', '5s penalty for pit entry line');
INSERT INTO race_results (race_id, driver_id, qualifying_position, finish_position, points, fastest_lap, status, penalties) VALUES (2, 10, 9, 10, 1, 91.990, 'Finished', 'Mechanical issue in final stint');

-------------------------------------------------------------------------------
-- PIT STOPS
-------------------------------------------------------------------------------
INSERT INTO pit_stops (race_id, driver_id, lap_number, stop_duration_ms, tyre_compound, reason) VALUES (1, 1, 18, 2145, 'Soft', 'Scheduled tyre change');
INSERT INTO pit_stops (race_id, driver_id, lap_number, stop_duration_ms, tyre_compound, reason) VALUES (1, 3, 17, 2068, 'Soft', 'Covered undercut threat');
INSERT INTO pit_stops (race_id, driver_id, lap_number, stop_duration_ms, tyre_compound, reason) VALUES (1, 7, 20, 2360, 'Medium', 'Front wing inspection');
INSERT INTO pit_stops (race_id, driver_id, lap_number, stop_duration_ms, tyre_compound, reason) VALUES (1, 10, 16, 2488, 'Hard', 'Wheel nut issue');
INSERT INTO pit_stops (race_id, driver_id, lap_number, stop_duration_ms, tyre_compound, reason) VALUES (2, 1, 22, 2099, 'Medium', 'Dry-to-dry strategy');
INSERT INTO pit_stops (race_id, driver_id, lap_number, stop_duration_ms, tyre_compound, reason) VALUES (2, 4, 21, 2125, 'Medium', 'Undercut response');
INSERT INTO pit_stops (race_id, driver_id, lap_number, stop_duration_ms, tyre_compound, reason) VALUES (2, 6, 24, 2195, 'Hard', 'Long-run strategy');
INSERT INTO pit_stops (race_id, driver_id, lap_number, stop_duration_ms, tyre_compound, reason) VALUES (2, 10, 23, 2650, 'Soft', 'Mechanical check');

-------------------------------------------------------------------------------
-- INCIDENTS
-------------------------------------------------------------------------------
INSERT INTO incidents (race_id, driver_id, incident_type, severity, lap_number, short_description) VALUES
(1, 7, 'Unsafe release', 'Medium', 19, 'Released into the path of another car during a crowded stop sequence');
INSERT INTO incidents (race_id, driver_id, incident_type, severity, lap_number, short_description) VALUES
(1, 10, 'Pit lane speeding', 'High', 16, 'Exceeded pit lane speed limit by a small margin');
INSERT INTO incidents (race_id, driver_id, incident_type, severity, lap_number, short_description) VALUES
(2, 6, 'Track limits', 'Low', 14, 'Repeated excursions at exit of final corner');
INSERT INTO incidents (race_id, driver_id, incident_type, severity, lap_number, short_description) VALUES
(2, 10, 'Mechanical issue', 'High', 31, 'Gearbox warning light triggered in final stint');

-------------------------------------------------------------------------------
-- PERFORMANCE METRICS
-------------------------------------------------------------------------------
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (1, 1, 92.880, 181.40, 6.20, 4, 1);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (2, 1, 93.220, 179.80, 5.10, 2, 0);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (3, 1, 92.100, 182.20, 7.40, 6, 1);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (4, 1, 93.500, 178.60, 4.80, 3, 1);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (5, 1, 94.010, 177.30, 4.20, 1, 0);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (6, 1, 92.700, 180.50, 5.60, 3, 1);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (7, 1, 93.800, 179.10, 6.90, 2, 2);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (8, 1, 92.540, 183.10, 7.10, 5, 0);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (9, 1, 94.300, 176.90, 4.00, 1, 1);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (10, 1, 93.260, 180.00, 6.40, 4, 2);

INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (1, 2, 89.950, 182.10, 5.10, 5, 0);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (2, 2, 90.520, 180.00, 4.90, 4, 0);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (3, 2, 90.080, 181.60, 5.80, 4, 1);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (4, 2, 89.980, 179.50, 4.60, 5, 0);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (5, 2, 91.300, 177.90, 4.40, 2, 1);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (6, 2, 90.910, 180.80, 5.20, 3, 1);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (7, 2, 90.640, 179.70, 5.00, 4, 0);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (8, 2, 91.020, 183.50, 6.10, 3, 1);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (9, 2, 91.220, 177.80, 4.30, 2, 1);
INSERT INTO performance_metrics (driver_id, race_id, avg_lap_time, top_speed, tyre_degradation, overtakes, mistakes) VALUES (10, 2, 91.950, 180.20, 5.90, 1, 2);

-------------------------------------------------------------------------------
-- PRE-FINALE SYNTHETIC EXTENSION
-- Preserves the curated rows above and fills missing driver/race combinations
-- for Rounds 1-5. Round 6 stays scheduled, but its team points are loaded
-- later by finale_insert.sql during the final reveal.
-------------------------------------------------------------------------------
INSERT INTO race_results (
  race_id,
  driver_id,
  qualifying_position,
  finish_position,
  points,
  fastest_lap,
  status,
  penalties
)
WITH team_form AS (
  SELECT /*+ MATERIALIZE */
    team_id,
    0.5 + DBMS_RANDOM.VALUE AS form_factor
  FROM teams
),
candidates AS (
  SELECT /*+ MATERIALIZE */
    r.race_id,
    r.weather_condition,
    d.driver_id,
    d.driver_code,
    existing.existing_results,
    ROW_NUMBER() OVER (
      PARTITION BY r.race_id
      ORDER BY DBMS_RANDOM.VALUE / tf.form_factor, d.driver_id
    ) AS qualifying_rank,
    ROW_NUMBER() OVER (
      PARTITION BY r.race_id
      ORDER BY DBMS_RANDOM.VALUE / tf.form_factor, d.driver_id
    ) AS finish_rank,
    CASE r.race_id
      WHEN 1 THEN 92.000
      WHEN 2 THEN 89.500
      WHEN 3 THEN 84.800
      WHEN 4 THEN 87.300
      WHEN 5 THEN 91.700
      ELSE 96.100
    END AS base_lap
  FROM races r
  CROSS JOIN drivers d
  JOIN team_form tf ON tf.team_id = d.team_id
  JOIN (
    SELECT r2.race_id, COUNT(rr.result_id) AS existing_results
    FROM races r2
    LEFT JOIN race_results rr ON rr.race_id = r2.race_id
    GROUP BY r2.race_id
  ) existing ON existing.race_id = r.race_id
  LEFT JOIN race_results already_seeded
    ON already_seeded.race_id = r.race_id
   AND already_seeded.driver_id = d.driver_id
  WHERE already_seeded.result_id IS NULL
    AND r.race_id < 6
),
scored AS (
  SELECT /*+ MATERIALIZE */
    race_id,
    driver_id,
    existing_results + qualifying_rank AS qualifying_position,
    existing_results + finish_rank AS finish_position,
    base_lap,
    TRUNC(DBMS_RANDOM.VALUE(0, 100)) AS incident_score,
    TRUNC(DBMS_RANDOM.VALUE(0, 1500)) AS lap_offset
  FROM candidates
)
SELECT
  race_id,
  driver_id,
  qualifying_position,
  CASE WHEN incident_score < 4 THEN NULL ELSE finish_position END AS finish_position,
  CASE
    WHEN incident_score < 4 THEN 0
    WHEN incident_score < 11 THEN GREATEST(
      CASE finish_position
        WHEN 1 THEN 25
        WHEN 2 THEN 18
        WHEN 3 THEN 15
        WHEN 4 THEN 12
        WHEN 5 THEN 10
        WHEN 6 THEN 8
        WHEN 7 THEN 6
        WHEN 8 THEN 4
        WHEN 9 THEN 2
        WHEN 10 THEN 1
        ELSE 0
      END - 2,
      0
    )
    ELSE
      CASE finish_position
        WHEN 1 THEN 25
        WHEN 2 THEN 18
        WHEN 3 THEN 15
        WHEN 4 THEN 12
        WHEN 5 THEN 10
        WHEN 6 THEN 8
        WHEN 7 THEN 6
        WHEN 8 THEN 4
        WHEN 9 THEN 2
        WHEN 10 THEN 1
        ELSE 0
      END
  END AS points,
  ROUND(base_lap + (finish_position * 0.085) + ((lap_offset - 600) / 1000), 3) AS fastest_lap,
  CASE WHEN incident_score < 4 THEN 'DNF' ELSE 'Finished' END AS status,
  CASE
    WHEN incident_score < 4 THEN 'Mechanical retirement'
    WHEN incident_score < 11 THEN '5s penalty for track limits'
    ELSE NULL
  END AS penalties
FROM scored;

INSERT INTO performance_metrics (
  driver_id,
  race_id,
  avg_lap_time,
  top_speed,
  tyre_degradation,
  overtakes,
  mistakes
)
SELECT
  rr.driver_id,
  rr.race_id,
  ROUND(rr.fastest_lap + 0.450 + (TRUNC(DBMS_RANDOM.VALUE(0, 1800)) / 1000), 3),
  ROUND(
    CASE
      WHEN LOWER(r.weather_condition) LIKE '%rain%' THEN 171.0
      WHEN LOWER(r.weather_condition) LIKE '%damp%' THEN 174.5
      ELSE 181.0
    END + ((TRUNC(DBMS_RANDOM.VALUE(0, 1000)) - 450) / 100),
    2
  ),
  ROUND(3.20 + (TRUNC(DBMS_RANDOM.VALUE(0, 560)) / 100), 2),
  GREATEST(rr.qualifying_position - NVL(rr.finish_position, 100), 0) +
    TRUNC(DBMS_RANDOM.VALUE(0, 4)),
  TRUNC(DBMS_RANDOM.VALUE(0, 3))
FROM race_results rr
JOIN races r ON r.race_id = rr.race_id
JOIN drivers d ON d.driver_id = rr.driver_id
LEFT JOIN performance_metrics already_seeded
  ON already_seeded.race_id = rr.race_id
 AND already_seeded.driver_id = rr.driver_id
WHERE already_seeded.metric_id IS NULL;

INSERT INTO pit_stops (
  race_id,
  driver_id,
  lap_number,
  stop_duration_ms,
  tyre_compound,
  reason
)
SELECT
  rr.race_id,
  rr.driver_id,
  12 + TRUNC(DBMS_RANDOM.VALUE(0, 26)),
  1980 + TRUNC(DBMS_RANDOM.VALUE(0, 1470)),
  CASE TRUNC(DBMS_RANDOM.VALUE(0, 4))
    WHEN 0 THEN 'Soft'
    WHEN 1 THEN 'Medium'
    WHEN 2 THEN 'Hard'
    ELSE 'Intermediate'
  END,
  CASE TRUNC(DBMS_RANDOM.VALUE(0, 6))
    WHEN 0 THEN 'Scheduled tyre change'
    WHEN 1 THEN 'Undercut response'
    WHEN 2 THEN 'Long-run strategy'
    WHEN 3 THEN 'Front wing inspection'
    WHEN 4 THEN 'Weather crossover'
    ELSE 'Vibration check'
  END
FROM race_results rr
LEFT JOIN pit_stops already_seeded
  ON already_seeded.race_id = rr.race_id
 AND already_seeded.driver_id = rr.driver_id
WHERE already_seeded.pit_stop_id IS NULL
  AND DBMS_RANDOM.VALUE(0, 100) < 72;

INSERT INTO incidents (
  race_id,
  driver_id,
  incident_type,
  severity,
  lap_number,
  short_description
)
SELECT
  race_id,
  driver_id,
  CASE itype_pick
    WHEN 0 THEN 'Track limits'
    WHEN 1 THEN 'Unsafe release'
    WHEN 2 THEN 'Mechanical issue'
    WHEN 3 THEN 'Contact'
    WHEN 4 THEN 'Pit lane speeding'
    ELSE 'Spin'
  END,
  CASE
    WHEN status = 'DNF' THEN 'High'
    WHEN severity_pick = 0 THEN 'Low'
    WHEN severity_pick = 1 THEN 'Medium'
    ELSE 'High'
  END,
  1 + ilap_pick,
  'Synthetic steward note generated from timing, telemetry and pit wall observations'
FROM (
  SELECT /*+ MATERIALIZE */
    rr.race_id,
    rr.driver_id,
    rr.status,
    TRUNC(DBMS_RANDOM.VALUE(0, 6)) AS itype_pick,
    TRUNC(DBMS_RANDOM.VALUE(0, 3)) AS severity_pick,
    TRUNC(DBMS_RANDOM.VALUE(0, 44)) AS ilap_pick
  FROM race_results rr
  LEFT JOIN incidents already_seeded
    ON already_seeded.race_id = rr.race_id
   AND already_seeded.driver_id = rr.driver_id
  WHERE already_seeded.incident_id IS NULL
    AND (rr.status = 'DNF' OR DBMS_RANDOM.VALUE(0, 100) < 16)
);

COMMIT;

-------------------------------------------------------------------------------
-- INDEXES AND ANALYTICS VIEWS
-------------------------------------------------------------------------------
CREATE UNIQUE INDEX ux_results_race_driver ON race_results (race_id, driver_id);
CREATE UNIQUE INDEX ux_perf_race_driver ON performance_metrics (race_id, driver_id);
CREATE UNIQUE INDEX ux_team_points_race_team ON team_race_points (race_id, team_id);
CREATE INDEX ix_drivers_team ON drivers (team_id);
CREATE INDEX ix_pit_race_driver ON pit_stops (race_id, driver_id);
CREATE INDEX ix_inc_race_driver ON incidents (race_id, driver_id);

CREATE OR REPLACE VIEW driver_standings AS
SELECT
  d.driver_id,
  d.driver_code,
  d.driver_label,
  d.driver_group,
  d.simulator_rig,
  d.vehicle_setup,
  d.driving_style,
  t.team_name,
  SUM(rr.points) AS total_points,
  COUNT(CASE WHEN rr.status = 'Finished' THEN 1 END) AS finishes,
  COUNT(CASE WHEN rr.status = 'DNF' THEN 1 END) AS dnfs,
  MIN(rr.finish_position) AS best_finish,
  ROUND(AVG(pm.avg_lap_time), 3) AS avg_lap_time,
  ROUND(AVG(pm.top_speed), 2) AS avg_top_speed
FROM drivers d
JOIN teams t ON t.team_id = d.team_id
LEFT JOIN race_results rr ON rr.driver_id = d.driver_id
LEFT JOIN performance_metrics pm
  ON pm.driver_id = rr.driver_id
 AND pm.race_id = rr.race_id
GROUP BY
  d.driver_id,
  d.driver_code,
  d.driver_label,
  d.driver_group,
  d.simulator_rig,
  d.vehicle_setup,
  d.driving_style,
  t.team_name;

CREATE OR REPLACE VIEW team_standings AS
SELECT
  t.team_id,
  t.team_name,
  t.engineering_focus,
  COUNT(DISTINCT d.driver_id) AS drivers,
  SUM(rr.points) AS total_points,
  ROUND(AVG(pm.top_speed), 2) AS avg_top_speed,
  ROUND(AVG(pm.tyre_degradation), 2) AS avg_tyre_degradation,
  COUNT(i.incident_id) AS incident_count
FROM teams t
JOIN drivers d ON d.team_id = t.team_id
LEFT JOIN race_results rr ON rr.driver_id = d.driver_id
LEFT JOIN performance_metrics pm
  ON pm.driver_id = rr.driver_id
 AND pm.race_id = rr.race_id
LEFT JOIN incidents i
  ON i.driver_id = d.driver_id
 AND i.race_id = rr.race_id
GROUP BY
  t.team_id,
  t.team_name,
  t.engineering_focus;

CREATE OR REPLACE VIEW championship_team_standings AS
SELECT
  ts.team_id,
  ts.team_name,
  ts.engineering_focus,
  ts.drivers,
  ts.total_points AS pre_finale_points,
  NVL(SUM(CASE WHEN r.race_name = 'Round 6: Finale Preview' THEN trp.points ELSE 0 END), 0) AS round6_points,
  ts.total_points +
    NVL(SUM(CASE WHEN r.race_name = 'Round 6: Finale Preview' THEN trp.points ELSE 0 END), 0) AS final_total_points,
  MAX(CASE WHEN r.race_name = 'Round 6: Finale Preview' THEN trp.publication_status END) AS round6_status,
  MAX(CASE WHEN r.race_name = 'Round 6: Finale Preview' THEN trp.recorded_at END) AS round6_recorded_at
FROM team_standings ts
LEFT JOIN team_race_points trp ON trp.team_id = ts.team_id
LEFT JOIN races r ON r.race_id = trp.race_id
GROUP BY
  ts.team_id,
  ts.team_name,
  ts.engineering_focus,
  ts.drivers,
  ts.total_points;

CREATE OR REPLACE VIEW race_summary AS
SELECT
  r.race_id,
  r.race_name,
  r.circuit,
  r.race_date,
  r.weather_condition,
  COUNT(rr.result_id) AS classified_entries,
  COUNT(CASE WHEN rr.status = 'DNF' THEN 1 END) AS retirements,
  ROUND(AVG(pm.avg_lap_time), 3) AS field_avg_lap_time,
  ROUND(AVG(ps.stop_duration_ms), 0) AS avg_pit_stop_ms,
  COUNT(DISTINCT i.incident_id) AS incident_count
FROM races r
LEFT JOIN race_results rr ON rr.race_id = r.race_id
LEFT JOIN performance_metrics pm
  ON pm.race_id = rr.race_id
 AND pm.driver_id = rr.driver_id
LEFT JOIN pit_stops ps
  ON ps.race_id = rr.race_id
 AND ps.driver_id = rr.driver_id
LEFT JOIN incidents i
  ON i.race_id = rr.race_id
 AND i.driver_id = rr.driver_id
GROUP BY
  r.race_id,
  r.race_name,
  r.circuit,
  r.race_date,
  r.weather_condition;

COMMIT;
