## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent

{{- if .Values.client.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-optimizer.fullname" . }}-st-config
  labels:
    app.kubernetes.io/component: client
    {{- include "ai-optimizer.labels" . | nindent 4}}
data:
  config.toml: |
    [global]
    disableWidgetStateDuplicationWarning = true

    [browser]
    gatherUsageStats = false
    serverAddress = "0.0.0.0"

    [server]
    port = "8501"
    headless = true
    fileWatcherType = "none"
    {{- $path := include "ai-optimizer.getPath" . | trimSuffix "/" }}
    {{- if ne $path "" }}
    baseUrlPath = {{ $path | quote }}
    {{- end }}
    {{- if .Values.client.ssl.certFile }}
    sslCertFile = {{ .Values.client.ssl.certFile | quote }}
    {{- end }}
    {{- if .Values.client.ssl.keyFile }}
    sslKeyFile = {{ .Values.client.ssl.keyFile | quote }}
    {{- end }}

    [client]
    toolbarMode = "minimal"
{{ end -}}