## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent tolerations streamlit snakecase

{{- if .Values.client.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-optimizer.fullname" . }}-client
  labels:
    app.kubernetes.io/component: client
    {{- include "ai-optimizer.labels" . | nindent 4}}
spec:
  {{- if not .Values.client.autoscaling.enabled }}
  replicas: {{ .Values.client.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: client
      {{- include "ai-optimizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/client-cookie-secret: {{ include "ai-optimizer.client.cookieSecretChecksum" . | quote }}
        checksum/client-password-secret: {{ include "ai-optimizer.client.passwordSecretChecksum" . | quote }}
        checksum/client-env-secret: {{ include "ai-optimizer.client.envSecretChecksum" . | quote }}
        {{- with .Values.client.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/component: client
        {{- include "ai-optimizer.labels" . | nindent 8 }}
        {{- with .Values.client.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        fsGroup: 10001
      {{- include "ai-optimizer.imagePullSecrets" (dict "local" .Values.client.imagePullSecrets "global" .Values.global.imagePullSecrets) | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "ai-optimizer.image" (dict "image" .Values.client.image "global" .Values.global "appVersion" .Chart.AppVersion) | quote }}
          imagePullPolicy: {{ .Values.client.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          env:
            - name: AIO_ENV
              value: {{ .Values.global.env | quote }}
            - name: AIO_SERVER_URL
              value: {{ include "ai-optimizer.server.serviceUrl" . }}
            - name: AIO_SERVER_PORT
              value: {{ .Values.server.service.port | default 8000 | quote }}
            - name: AIO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ai-optimizer.apiSecretName" . }}
                  key: {{ include "ai-optimizer.apiSecretKey" . }}
            - name: AIO_CLIENT_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ai-optimizer.client.cookieSecretName" . }}
                  key: {{ include "ai-optimizer.client.cookieSecretKey" . }}
            {{- if or (.Values.client.password | trim) (.Values.client.passwordSecretName | trim) }}
            - name: AIO_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ai-optimizer.client.passwordSecretName" . }}
                  key: {{ include "ai-optimizer.client.passwordSecretKey" . }}
            {{- end }}
            {{- if .Values.client.oci.sourceBucketCompartmentId }}
            - name: AIO_OCI_SOURCE_BUCKET_COMPARTMENT_ID
              value: {{ .Values.client.oci.sourceBucketCompartmentId | quote }}
            {{- end }}
            {{- if .Values.client.oci.sourceBucketName }}
            - name: AIO_OCI_SOURCE_BUCKET_NAME
              value: {{ .Values.client.oci.sourceBucketName | quote }}
            {{- end }}
          ports:
            - name: client-port
              containerPort: 8501
              protocol: TCP
          {{- if .Values.client.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ include "ai-optimizer.getPath" . }}ping
              port: client-port
              {{- if .Values.client.ssl.enabled }}
              scheme: HTTPS
              {{- end }}
            {{- with omit .Values.client.livenessProbe "enabled" }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.client.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ include "ai-optimizer.getPath" . }}ping
              port: client-port
              {{- if .Values.client.ssl.enabled }}
              scheme: HTTPS
              {{- end }}
            {{- with omit .Values.client.readinessProbe "enabled" }}
               {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- if .Values.client.resources }}
          resources:
            {{- toYaml .Values.client.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: "/app/tmp"
            - name: streamlit-config
              mountPath: /app/.streamlit
            - name: env-config
              mountPath: /app/src/.env.{{ .Values.global.env }}
              subPath: {{ include "ai-optimizer.client.envSecretKey" . }}
              readOnly: true
          {{- with .Values.client.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: streamlit-config
          configMap:
            name: {{ include "ai-optimizer.fullname" . }}-st-config
        - name: env-config
          secret:
            secretName: {{ include "ai-optimizer.client.envSecretName" . }}
      {{- with .Values.client.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end -}}
