## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent

# Database Privileged User Secret
{{- if .Values.server.database }}
{{- if .Values.server.database.type }}
{{- $secretName := include "server.databasePrivSecret" . }}
{{- $secret_existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if not $secret_existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/component: database
    {{- include "global.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  username: {{ if eq (include "server.database.isADB" .) "true" }}"ADMIN"{{ else }}"SYSTEM"{{ end }}
  password: {{ include "server.randomPassword" . | quote }}
  {{- if eq (include "server.database.isSIDB" .) "true" }}
  {{ default "service" .Values.server.database.privAuthN.serviceKey }}: "{{ .Release.Name }}-{{ include "server.database.dbName" . }}-1521:1521/FREEPDB1"
  {{- else if eq (include "server.database.isADBFree" .) "true" }}
  {{ default "service" .Values.server.database.privAuthN.serviceKey }}: "{{ .Release.Name }}-{{ include "server.database.dbName" . }}-1521:1521/FREEPDB1"
  {{- else if eq (include "server.database.isADBS" .) "true" }}
  {{ default "service" .Values.server.database.privAuthN.serviceKey }}: {{ .Values.server.database.adb.serviceName | quote }}
  {{- else if eq (include "server.database.isOther" .) "true" }}
    {{- if and .Values.server.database.other.dsn (ne (.Values.server.database.other.dsn | trim) "") }}
  {{ default "service" .Values.server.database.privAuthN.serviceKey }}: "{{ .Values.server.database.other.dsn }}"
    {{- else }}
  {{ default "service" .Values.server.database.privAuthN.serviceKey }}: "{{ .Values.server.database.other.host }}:{{ .Values.server.database.other.port }}/{{ .Values.server.database.other.serviceName }}"
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
