{{/* Copyright (c) 2024, 2026, Oracle and/or its affiliates.
Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
spell-checker: ignore nindent sidb

Database Service (SIDB-FREE or ADB-FREE in-cluster container DB) */}}
{{- if eq (include "ai-optimizer.server.database.isContainerDB" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-optimizer.server.database.serviceName" . }}
  labels:
    app.kubernetes.io/component: database
    {{- include "ai-optimizer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: oracle-db
      protocol: TCP
      port: 1521
      targetPort: 1521
  selector:
    app.kubernetes.io/component: database
    {{- include "ai-optimizer.selectorLabels" . | nindent 4 }}
{{- end }}
