name: 🐛 Bug report
description: Submit a bug report to help us improve the AI Optimizer and Toolkit
labels: ["type:bug", "status:needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this problem!
        We really appreciate the community's efforts to improve the AI Optimizer and Toolkit.

        If you are not sure whether you have found a bug, please consider asking in our [Slack Channel](https://oracledevs.slack.com/archives/C089NPXG8AU) first.
  - type: checkboxes
    attributes:
      label: Checklist
      description: Please confirm and check all the following options.
      options:
        - label: I have searched the [existing issues](https://github.com/oracle/ai-optimizer/issues) for similar issues.
          required: true
        - label: I added a very descriptive title to this issue.
          required: true
        - label: I have provided sufficient information below to help reproduce this issue.
          required: true
  - type: textarea
    attributes:
      label: Summary
      description: Type here a clear and concise description of the problem. Aim for 2-3 sentences.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Please provide the steps we should take to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Explain what you expect to happen when you go through the steps above, assuming there were no bugs.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behavior
      placeholder: |
        Error message or applicable log output:
        ```
        ...
        ```
      description: |
        Explain the buggy behavior you experience when you go through the steps above.
        If you have error messages or stack traces please provide them here as well.
        If applicable, add screenshots to help explain your problem.

        _Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in._
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Is this a regression?
      description: Did this use to work the way you expected in the past?
      options:
        - label: Yes, this used to work in a previous version.
          required: false
  - type: textarea
    attributes:
      label: Debug info
      description: |
        Please share some system information related to the environment your app is running in.

        Example:
          - **Version**: 1.13.0 _(found in `common/_version.py`)_
          - **Python version**: 3.11 _(get it with `$ python --version`)_
          - **Operating System**: MacOs 12.6
          - **Browser**: Chrome
      value: |
        - Version:
        - Python version:
        - Operating System:
        - Browser:
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        _Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in._
    validations:
      required: false
