spring:
  datasource:
    url: ${{spring.datasource.url]}}
    username: ${{spring.datasource.username]}}
    password: ${{spring.datasource.password]}}
  ai:
    vectorstore:
      oracle:
        distance-type: {vector_search[distance_metric]}
        remove-existing-vector-store-table: True
        initialize-schema: True
        index-type: {vector_search[index_type]}
    openai:
      base-url: {ll_model[api_base]}
      api-key:  {ll_model[api_key]}
      chat:
        options:
          temperature: {ll_model[temperature]}
          presencePenalty: {ll_model[presence_penalty]}
          frequencyPenalty: {ll_model[frequency_penalty]}
          maxTokens: {ll_model[max_tokens]}
          topP: {ll_model[top_p]}
          model: {ll_model[id]}
      embedding:
        options:
          model: {vector_search[id]}
    ollama:
      base-url: "http://ollama.ollama.svc.cluster.local:11434"
      chat:
        options:
          temperature: {ll_model[temperature]}
          presence-penalty: {ll_model[presence_penalty]}
          frequency-penalty: {ll_model[frequency_penalty]}
          num-predict: {ll_model[max_tokens]}
          top-p: {ll_model[top_p]}
          model: {ll_model[id]}
      embedding:
        options: 
          model: {vector_search[id]}        
aims:
  sys_instr: \"{sys_prompt}\"
  vectortable:
    name: {vector_search[vector_store]}
  rag_params: 
    search_type: Similarity
    top_k: {vector_search[top_k]}
