-- Mortgage Lending demo
-- All data in this script is fictional and synthetic. It contains no PII.
-- Run only in a schema that may be reset: this script drops its demo objects.

BEGIN EXECUTE IMMEDIATE 'DROP VIEW mortgage_application_summary'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE mortgage_applications PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE lenders PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE lenders (
  lender_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lender_name VARCHAR2(100) NOT NULL
);

CREATE TABLE mortgage_applications (
  application_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_reference VARCHAR2(30) NOT NULL UNIQUE,
  mortgagor_label VARCHAR2(30) NOT NULL UNIQUE,
  lender_id NUMBER NOT NULL REFERENCES lenders(lender_id),
  application_type VARCHAR2(30) NOT NULL,
  property_location VARCHAR2(80) NOT NULL,
  employment_type VARCHAR2(40) NOT NULL,
  verified_annual_income NUMBER(12,2) NOT NULL,
  verified_other_income NUMBER(12,2) DEFAULT 0 NOT NULL,
  monthly_committed_expenditure NUMBER(12,2) NOT NULL,
  monthly_household_expenditure NUMBER(12,2) NOT NULL,
  dependant_count NUMBER(2) DEFAULT 0 NOT NULL,
  property_value NUMBER(12,2) NOT NULL,
  requested_loan_amount NUMBER(12,2) NOT NULL,
  mortgage_term_years NUMBER(2) NOT NULL,
  repayment_type VARCHAR2(30) NOT NULL,
  product_rate NUMBER(5,2) NOT NULL,
  CONSTRAINT ck_mortgage_application_type CHECK (application_type IN ('Purchase', 'Remortgage')),
  CONSTRAINT ck_mortgage_repayment CHECK (repayment_type = 'Capital and interest')
);

INSERT INTO lenders (lender_name)
VALUES ('Harbourstone Home Finance (fictional)');

INSERT INTO mortgage_applications (
  application_reference, mortgagor_label, lender_id, application_type, property_location,
  employment_type, verified_annual_income, verified_other_income, monthly_committed_expenditure,
  monthly_household_expenditure, dependant_count, property_value, requested_loan_amount,
  mortgage_term_years, repayment_type, product_rate
)
  SELECT 'APP-001', 'MORTGAGOR_001', 1, 'Purchase', 'Leeds', 'Permanent employed', 62000, 0, 320, 1450, 0, 320000, 256000, 30, 'Capital and interest', 4.89 FROM dual UNION ALL
  SELECT 'APP-002', 'MORTGAGOR_002', 1, 'Purchase', 'Leeds', 'Permanent employed', 48000, 4000, 610, 1720, 1, 285000, 242250, 30, 'Capital and interest', 5.14 FROM dual UNION ALL
  SELECT 'APP-003', 'MORTGAGOR_003', 1, 'Remortgage', 'Bristol', 'Fixed-term contract', 76000, 0, 980, 2100, 2, 475000, 332500, 25, 'Capital and interest', 4.99 FROM dual UNION ALL
  SELECT 'APP-004', 'MORTGAGOR_004', 1, 'Purchase', 'Manchester', 'Self-employed', 54000, 6000, 450, 1680, 1, 350000, 297500, 30, 'Capital and interest', 5.29 FROM dual UNION ALL
  SELECT 'APP-005', 'MORTGAGOR_005', 1, 'Purchase', 'Birmingham', 'Permanent employed', 39500, 0, 770, 1510, 0, 265000, 238500, 30, 'Capital and interest', 5.39 FROM dual UNION ALL
  SELECT 'APP-006', 'MORTGAGOR_006', 1, 'Remortgage', 'Leeds', 'Permanent employed', 88000, 12000, 420, 2380, 3, 520000, 338000, 25, 'Capital and interest', 4.79 FROM dual UNION ALL
  SELECT 'APP-007', 'MORTGAGOR_007', 1, 'Purchase', 'Bristol', 'Fixed-term contract', 51000, 0, 890, 1900, 1, 410000, 369000, 30, 'Capital and interest', 5.49 FROM dual UNION ALL
  SELECT 'APP-008', 'MORTGAGOR_008', 1, 'Purchase', 'Manchester', 'Permanent employed', 72000, 0, 260, 1590, 0, 390000, 273000, 25, 'Capital and interest', 4.89 FROM dual;

CREATE OR REPLACE VIEW mortgage_application_summary AS
SELECT
  a.application_reference,
  a.mortgagor_label,
  a.application_type,
  a.property_location,
  a.employment_type,
  a.verified_annual_income + a.verified_other_income AS total_verified_annual_income,
  a.monthly_committed_expenditure,
  a.monthly_household_expenditure,
  a.dependant_count,
  a.property_value,
  a.requested_loan_amount,
  ROUND(a.requested_loan_amount / a.property_value * 100, 2) AS loan_to_value_pct,
  ROUND(a.requested_loan_amount / (a.verified_annual_income + a.verified_other_income), 2) AS loan_to_income_multiple,
  a.mortgage_term_years,
  a.repayment_type,
  a.product_rate
FROM mortgage_applications a;

COMMIT;
