#!/usr/bin/env python3
"""
Copyright (c) 2024, 2026, Oracle and/or its affiliates.
Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

Container / CLI entrypoint — configures the environment and launches the server (uvicorn) or client (streamlit).
"""
# spell-checker: ignore streamlit sslcertfile sslkeyfile

import json
import os
import re
import secrets
import shutil
import sys
import tomllib
from pathlib import Path
from urllib.parse import urlparse

from dotenv import load_dotenv

from dev_auth_credentials import load_or_create_bootstrap_credential, load_or_create_web_client_secret
from net_addressing import client_web_redirect_uri, ensure_ssl_cert, parse_bool

_LEGACY_DEFAULT_WEB_REDIRECT_URI = "http://localhost:8501/oauth2callback"
_GENERATED_OIDC_CONFIG_MARKER = "# Generated by the All-In-One development OIDC launcher"


def setup_pythonpath(script_dir: Path) -> None:
    """Prepend the src/ directory to PYTHONPATH so module imports resolve."""
    current = os.environ.get("PYTHONPATH", "")
    os.environ["PYTHONPATH"] = str(script_dir) + (":" + current if current else "")


def load_env_file(script_dir: Path) -> None:
    """Load .env.{AIO_ENV} variables without overwriting existing environment variables.

    Pod / container env vars always take precedence over values in the .env file.
    """
    env_name = os.environ.get("AIO_ENV", "dev")
    env_file = script_dir / f".env.{env_name}"
    if env_file.is_file():
        load_dotenv(env_file, override=False)


def prepare_oci_config() -> None:
    """Copy a read-only OCI config mount to a writable location and rewrite key_file paths."""
    oci_dir = Path("/app/.oci")
    oci_runtime_dir = Path("/app/runtime/.oci")
    config_file = oci_dir / "config"

    if not config_file.is_file():
        return

    print(f"Found OCI Config file in: {oci_dir}; preparing writable copy in {oci_runtime_dir}")
    shutil.copytree(oci_dir, oci_runtime_dir, dirs_exist_ok=True)

    runtime_config = oci_runtime_dir / "config"
    content = runtime_config.read_text(encoding="utf-8")
    content = re.sub(
        r"^(key_file\s*=\s*)(.+)$",
        lambda m: m.group(1) + str(oci_runtime_dir / Path(m.group(2).strip()).name),
        content,
        flags=re.MULTILINE,
    )
    runtime_config.write_text(content, encoding="utf-8")

    os.environ["OCI_CLI_CONFIG_FILE"] = str(runtime_config)


def detect_component(script_dir: Path, arg: str) -> str:
    """Determine whether to start 'server' or 'client' from a CLI arg or directory structure."""
    if arg:
        return arg
    # Docker images remove the unused component directory
    if (script_dir / "server").is_dir() and not (script_dir / "client").is_dir():
        return "server"
    return "client"


def start_server(script_dir: Path) -> None:
    """Launch uvicorn for the FastAPI server, with optional TLS."""
    print("Starting Optimizer Server")
    args = [
        "uvicorn",
        "server.app.main:app",
        "--host",
        os.environ.get("AIO_SERVER_ADDRESS", "0.0.0.0"),
        "--port",
        os.environ.get("AIO_SERVER_PORT", "8000"),
    ]

    if os.environ.get("AIO_SERVER_SSL", "false").lower() == "true":
        cert, key = ensure_ssl_cert(script_dir, "AIO_SERVER_SSL_CERT_FILE", "AIO_SERVER_SSL_KEY_FILE")
        args.extend(["--ssl-certfile", str(cert), "--ssl-keyfile", str(key)])

    os.execvp("uvicorn", args)


def start_client(script_dir: Path) -> None:
    """Launch streamlit for the client UI, with optional TLS."""
    print("Starting Optimizer Client")
    args = [
        "streamlit",
        "run",
        str(script_dir / "client" / "app" / "main.py"),
        "--server.port",
        os.environ.get("AIO_CLIENT_PORT", "8501"),
        "--server.address",
        os.environ.get("AIO_CLIENT_ADDRESS", "localhost"),
    ]

    # server.cookieSecret is marked sensitive=True in Streamlit and is read
    # through its env var. Promote AIO_CLIENT_COOKIE_SECRET into
    # STREAMLIT_SERVER_COOKIE_SECRET so the value is inherited by execvp
    # without adding it to argv. If AIO var is unset, let Streamlit's own
    # per-process default handle the single-replica case.
    cookie_secret = os.environ.get("AIO_CLIENT_COOKIE_SECRET", "")
    if cookie_secret:
        os.environ["STREAMLIT_SERVER_COOKIE_SECRET"] = cookie_secret

    _prepare_development_oidc_streamlit_config(script_dir, cookie_secret)

    if parse_bool(os.environ.get("AIO_CLIENT_SSL")):
        cert, key = ensure_ssl_cert(script_dir, "AIO_CLIENT_SSL_CERT_FILE", "AIO_CLIENT_SSL_KEY_FILE")
        args.extend(["--server.sslCertFile", str(cert), "--server.sslKeyFile", str(key)])

    os.execvp("streamlit", args)


def _prepare_development_oidc_streamlit_config(script_dir: Path, cookie_secret: str) -> None:
    """Create local Streamlit OIDC settings when the built-in provider is active."""
    if not _uses_local_development_oidc(script_dir):
        return
    if _is_local_all_in_one(script_dir):
        bootstrap_credential = None
        if not os.environ.get("AIO_AUTH_DEV_ADMIN_PASSWORD"):
            bootstrap_credential = load_or_create_bootstrap_credential(script_dir)
            os.environ["AIO_AUTH_DEV_ADMIN_PASSWORD"] = bootstrap_credential.password
        if not os.environ.get("AIO_AUTH_DEV_WEB_CLIENT_SECRET"):
            os.environ["AIO_AUTH_DEV_WEB_CLIENT_SECRET"] = load_or_create_web_client_secret(
                script_dir,
                fallback=bootstrap_credential.web_client_secret if bootstrap_credential is not None else "",
            )
    config_dir = script_dir / "client" / "app" / ".streamlit"
    secrets_file = config_dir / "secrets.toml"
    secrets_file_exists = secrets_file.exists()
    issuer = os.environ.get("AIO_AUTH_DEV_ISSUER", "http://127.0.0.1:8765").rstrip("/")
    configured_redirect_uri = os.environ.get("AIO_AUTH_DEV_WEB_REDIRECT_URI")
    if configured_redirect_uri is None or not configured_redirect_uri.strip():
        redirect_uri = client_web_redirect_uri()
        os.environ["AIO_AUTH_DEV_WEB_REDIRECT_URI"] = redirect_uri
    else:
        redirect_uri = configured_redirect_uri
    web_client_secret = os.environ["AIO_AUTH_DEV_WEB_CLIENT_SECRET"]
    if secrets_file_exists:
        contents = secrets_file.read_text(encoding="utf-8")
        try:
            auth_config = tomllib.loads(contents).get("auth", {})
        except tomllib.TOMLDecodeError:
            return
        if not isinstance(auth_config, dict):
            return
        generated_config = (
            auth_config.get("client_id") == "platform-web-client"
            and auth_config.get("server_metadata_url") == f"{issuer}/.well-known/openid-configuration"
            and auth_config.get("client_kwargs") == {"scope": "openid profile email aio.api"}
            and auth_config.get("expose_tokens") == "access"
            and (
                _GENERATED_OIDC_CONFIG_MARKER in contents
                or (
                    isinstance(auth_config.get("redirect_uri"), str)
                    and auth_config.get("redirect_uri") in {redirect_uri, _LEGACY_DEFAULT_WEB_REDIRECT_URI}
                )
            )
        )
        placeholder_config = (
            auth_config.get("client_id") == "platform-web-client" and auth_config.get("client_secret") == ""
        )
        if not generated_config and not placeholder_config:
            return
        oidc_cookie_secret = cookie_secret or auth_config.get("cookie_secret") or secrets.token_urlsafe(48)
    else:
        oidc_cookie_secret = cookie_secret or secrets.token_urlsafe(48)
    config_dir.mkdir(parents=True, exist_ok=True)
    contents = "\n".join(
        (
            _GENERATED_OIDC_CONFIG_MARKER,
            "[auth]",
            f"redirect_uri = {json.dumps(redirect_uri)}",
            f"cookie_secret = {json.dumps(oidc_cookie_secret)}",
            'client_id = "platform-web-client"',
            f"client_secret = {json.dumps(web_client_secret)}",
            f"server_metadata_url = {json.dumps(f'{issuer}/.well-known/openid-configuration')}",
            'client_kwargs = { scope = "openid profile email aio.api" }',
            'expose_tokens = "access"',
            "",
        )
    )
    if secrets_file_exists:
        secrets_file.write_text(contents, encoding="utf-8")
    else:
        try:
            with secrets_file.open("x", encoding="utf-8") as streamlit_secrets:
                streamlit_secrets.write(contents)
        except FileExistsError:
            # A concurrent launcher or an operator-provided file won the race.
            return
    secrets_file.chmod(0o600)


def _uses_local_development_oidc(script_dir: Path) -> bool:
    """Return whether this client launch uses the built-in development provider."""
    if not _is_local_all_in_one(script_dir):
        return False
    auth_mode = os.environ.get("AIO_AUTH_MODE")
    if auth_mode == "dev":
        return True
    if auth_mode is not None:
        return False
    return any(
        os.environ.get(name)
        for name in ("DB_USERNAME", "DB_PASSWORD", "DB_DSN", "AIO_DB_USERNAME", "AIO_DB_PASSWORD", "AIO_DB_DSN")
    )


def _is_local_all_in_one(script_dir: Path) -> bool:
    """Return whether this source installation will connect to its local server."""
    if not (script_dir / "server").is_dir():
        return False
    hostname = urlparse(os.environ.get("AIO_SERVER_URL", "http://localhost")).hostname
    return hostname in {"localhost", "127.0.0.1", "::1", "0.0.0.0", "::"}


def main() -> None:
    """Configure the environment and launch the appropriate component."""
    script_dir = Path(__file__).resolve().parent
    setup_pythonpath(script_dir)
    load_env_file(script_dir)
    prepare_oci_config()

    arg = sys.argv[1] if len(sys.argv) > 1 else ""
    component = detect_component(script_dir, arg)

    if component == "server":
        start_server(script_dir)
    elif component == "client":
        start_client(script_dir)
    else:
        print("Usage: entrypoint.py [client|server]", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
