# Workflow for running tests on server code
name: Test Suite

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

  # Allows running this workflow manually
  workflow_dispatch:

jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    # Block merging if the job fails
    permissions:
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            src/.tox
          key: ${{ runner.os }}-pip-${{ hashFiles('src/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools uv
          uv pip install torch==2.9.0+cpu -f https://download.pytorch.org/whl/cpu/torch --system
          uv pip install -e ".[all-test]" --system

      - name: Run Pylint on IaC Code
        run: pylint opentofu

      - name: Run Pylint on Client Code
        run: pylint src/client

      - name: Run Pylint on Common Code
        run: pylint src/common

      # Linting errors not yet resolved in Server Code
      # - name: Run Pylint on Server Code
      #   run: pylint src/server

      - name: Run All Tests
        run: pytest tests -v --junitxml=test-results.xml --cov=src --cov-report=xml --cov-report=term

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results.xml
            coverage.xml
            .coverage
